<!-- FOOTER -->
<footer class="bg-[#070e18] text-white pt-14 pb-6 px-6">
  <div class="footer-grid max-w-[1280px] mx-auto grid grid-cols-[2fr_1fr_1fr_1fr] gap-[42px] pb-[42px] border-b border-white/10 mb-[26px]">
    <div>
      <div class="font-playfair text-[16px] font-bold text-gold mb-1" style="text-transform: uppercase;">{{ $content->com_name ?? 'JOURNEY WITH MR. J' }}</div>
      <div class="text-[11px] text-white mb-[15px]">WhatsApp Booking — Chat like a friend</div>
      <p class="text-[13px] leading-[1.7] mb-[17px] text-white">Rome's premier tour booking service, available 24/7 via WhatsApp. Curated experiences with expert local guides.</p>
      <div class="flex gap-2">
        <a href="#" class="w-[34px] h-[34px] bg-white/8 rounded-lg flex items-center justify-center text-white no-underline text-[14px] transition-all hover:bg-gold hover:text-navy">f</a>
        <a href="#" class="w-[34px] h-[34px] bg-white/8 rounded-lg flex items-center justify-center text-white no-underline text-[14px] transition-all hover:bg-gold hover:text-navy">&#128247;</a>
        <a href="#" class="w-[34px] h-[34px] bg-white/8 rounded-lg flex items-center justify-center text-white no-underline text-[14px] transition-all hover:bg-gold hover:text-navy">&#9834;</a>
        <a href="#" class="w-[34px] h-[34px] bg-white/8 rounded-lg flex items-center justify-center text-white no-underline text-[14px] transition-all hover:bg-gold hover:text-navy">&#9654;</a>
        <a href="#" class="w-[34px] h-[34px] bg-white/8 rounded-lg flex items-center justify-center text-white no-underline text-[14px] transition-all hover:bg-gold hover:text-navy">&#128172;</a>
      </div>
    </div>
    <div><h4 class="text-[12px] font-bold text-white tracking-[1.2px] uppercase mb-[15px]">Tours</h4><ul class="list-none"><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Colosseum Tours</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Vatican Tours</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Roman Forum</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Pantheon</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Borghese Gallery</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Trevi Fountain</a></li></ul></div>
    <div><h4 class="text-[12px] font-bold text-white tracking-[1.2px] uppercase mb-[15px]">Company</h4><ul class="list-none"><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">About Mr. J</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Our Guides</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Blog</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Reviews</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Become a Partner</a></li></ul></div>
    <div><h4 class="text-[12px] font-bold text-white tracking-[1.2px] uppercase mb-[15px]">Support</h4><ul class="list-none"><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">FAQ</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Contact Us</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">WhatsApp Us</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Cancellation Policy</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Privacy Policy</a></li><li class="mb-[9px]"><a href="#" class="text-[13px] text-white no-underline transition-colors hover:text-gold">Terms of Service</a></li></ul></div>
  </div>
  <div class="footer-grid max-w-[1280px] mx-auto flex items-center justify-between flex-wrap gap-[9px]">
    <p class="text-[12px] text-white">&copy; {{ date('Y') }} {{ $content->com_name ?? 'Journey With Mr. J' }}. All rights reserved.</p>
    <div class="flex gap-[17px]"><a href="#" class="text-[12px] text-white no-underline transition-colors hover:text-gold">Privacy Policy</a><a href="#" class="text-[12px] text-white no-underline transition-colors hover:text-gold">Terms</a><a href="#" class="text-[12px] text-white no-underline transition-colors hover:text-gold">Cookies</a><a href="#" class="text-[12px] text-white no-underline transition-colors hover:text-gold">Sitemap</a></div>
  </div>
</footer>
